(()=>{"use strict";
const resources=[
{number:"01",title:"Website from a survey",description:"The prompt used to design and deploy a website from survey results.",video:"",prompt:'In hinglish, survey me and make a suitable website that suits the results of the survey. Deploy it on my github repo "{NAME_OF_REPO}". Directly deploy in the main branch, make the site so responsive and smooth without compromising. Don’t limit yourself in just index.html, make the files that stable hosting on github pages need.'},
{number:"02",title:"Your next resource",description:"Add a video and a piece of code whenever this resource is ready.",video:"",code:{language:"javascript",filename:"example.js",content:'// Paste the exact code from your video here.\nconsole.log("Hello, CGX30");'}}
];
const list=document.querySelector("#resource-list");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const id=u=>{const m=String(u||"").match(/(?:youtu\.be\/|youtube(?:-nocookie)?\.com\/(?:watch\?v=|shorts\/|embed\/))([\w-]{6,})/);return m?m[1]:""};
const video=u=>{const i=id(u);return i?'<div class="video-shell"><iframe src="https://www.youtube-nocookie.com/embed/'+i+'" title="Video resource" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>':'<div class="video-placeholder"><span>VIDEO</span><strong>Coming soon.</strong><small>Add the YouTube link in resources.js</small></div>'};
const code=(x,key)=>'<div class="code-card"><div class="code-head"><span>'+esc(x.filename||"code.txt")+' · '+esc(x.language||"text")+'</span><button type="button" data-copy="'+key+'">COPY</button></div><pre id="'+key+'">'+esc(x.content||"")+'</pre></div>';
const block=(n,label,content)=>'<section class="resource-block"><aside>'+n+' / '+label+'</aside><div>'+content+'</div></section>';
function render(){list.innerHTML=resources.map((r,i)=>{let n=1,s='<article class="resource-entry reveal"><header><span>RESOURCE '+esc(r.number||String(i+1).padStart(2,"0"))+'</span><h2>'+esc(r.title||"Untitled")+'</h2><p>'+esc(r.description||"")+'</p></header>';if(r.video)s+=block(String(n++).padStart(2,"0"),"VIDEO",video(r.video));if(r.prompt)s+=block(String(n++).padStart(2,"0"),"PROMPT",code({filename:"prompt.txt",language:"text",content:r.prompt},"prompt-"+i));if(r.code)s+=block(String(n++).padStart(2,"0"),"CODE",code(r.code,"code-"+i));if(r.commands?.length)s+=block(String(n++).padStart(2,"0"),"COMMANDS",'<div class="command-list">'+r.commands.map((x,j)=>'<div class="command"><div><small>'+esc(x.name||"COMMAND")+'</small><pre id="cmd-'+i+"-"+j+'">'+esc(x.content||"")+'</pre></div><button type="button" data-copy="cmd-'+i+"-"+j+'">COPY</button></div>').join("")+"</div>");if(r.links?.length)s+=block(String(n++).padStart(2,"0"),"LINKS",'<div class="link-list">'+r.links.map(x=>'<a href="'+esc(x.url||"#")+'" target="_blank" rel="noopener noreferrer"><span>'+esc(x.label||x.url||"LINK")+'</span><b>↗</b></a>').join("")+"</div>");return s+"</article>"}).join("");document.querySelectorAll(".resource-entry").forEach(x=>x.classList.add("is-visible"))}
document.addEventListener("click",async e=>{const b=e.target.closest("[data-copy]");if(!b)return;const el=document.getElementById(b.dataset.copy);try{await navigator.clipboard.writeText(el.textContent);const old=b.textContent;b.textContent="COPIED";setTimeout(()=>b.textContent=old,1400)}catch{b.textContent="SELECT & COPY";setTimeout(()=>b.textContent="COPY",1400)}});
render();
const bar=document.querySelector(".progress span");addEventListener("scroll",()=>requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.transform="scaleX("+(max?scrollY/max:0)+")"}),{passive:true});
})();